# Generated by Django 5.2.4 on 2025-07-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_usercookiedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCookieData',
        ),
    ]
