# Generated by Django 5.2.4 on 2025-07-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_articles_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
    ]
